version: '3'
services:
  datascience-notebook:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=admin
